services:
  postgres:
    image: postgres:16
    container_name: teachers_help_db
    environment:
      POSTGRES_USER: teacher
      POSTGRES_PASSWORD: teacher_pass
      POSTGRES_DB: teachers_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
